### ISSUE TITLE
hook testing should be best practice for SHARED hooks

### ISSUE THREAD

**Issue by LiranBri** [nielsen-oss/docs#30]
currently, we say that hook testing is not preferred but component testing should test it along the way instead. this is true for an internal hook for the sake of the component.

however, when the hook is to be shared across components, it should be tested in isolation as a standalone hook and it is the best practice

**Comment by MatanBorenkraoutNielsen** [comment]
Addressed here: https://github.com/nielsen-oss/docs/pull/32
